#include "Player.hpp"
#include "SerializeUtility.hpp"
#include <boost/test/auto_unit_test.hpp>
#include <iostream>


BOOST_AUTO_TEST_CASE( PlayerConstructor )
{

  Player pl("Test Name",14);
  BOOST_CHECK(pl.GetName() == "Test Name");
  BOOST_CHECK_EQUAL( pl.GetId() , 14);

  BOOST_CHECK_EQUAL( pl.GetPurchaseState() , DONE );
  BOOST_CHECK_EQUAL( pl.GetBidState() , PASS_OUT );
  BOOST_CHECK_EQUAL( pl.HasPurchased() , false);


  BOOST_CHECK_EQUAL( pl.GetNumHumans() , 0);
  BOOST_CHECK_EQUAL( pl.GetNumRobots() , 0);

  pl.AddRobots(7);
  pl.AddHumans(3);

  BOOST_CHECK_EQUAL( pl.GetNumHumans() , 3);
  BOOST_CHECK_EQUAL( pl.GetNumRobots() , 7);

  pl.AddRobots(21);
  pl.AddHumans(5);

  BOOST_CHECK_EQUAL( pl.GetNumHumans() , 8);
  BOOST_CHECK_EQUAL( pl.GetNumRobots() , 28);

  pl.SetPurchaseState(INTERNALIZING);
  pl.SetBidState(PASS);
  pl.SetHasPurchased(true);

  BOOST_CHECK_EQUAL( pl.GetPurchaseState() , INTERNALIZING );
  BOOST_CHECK_EQUAL( pl.GetBidState() , PASS );
  BOOST_CHECK_EQUAL( pl.HasPurchased() , true);

  BOOST_CHECK(pl.OkStartup() == false);
  pl.SetOkStartup(true);
  BOOST_CHECK(pl.OkStartup() == true);
  pl.SetOkStartup(false);
  BOOST_CHECK(pl.OkStartup() == false);
  pl.SetOkStartup(true);
  BOOST_CHECK(pl.OkStartup() == true);

  pl.GetFactories().AddFactory(RESEARCH_FACTORY);
  pl.GetFactories().AddFactory(NEW_CHEMICALS_FACTORY);
  pl.GetFactories().AddFactory(NEW_CHEMICALS_FACTORY);
  pl.GetFactories().AddFactory(MOON_BASE_FACTORY);
  pl.GetFactories().AddFactory(SPACE_STATION_FACTORY);
  pl.GetFactories().AddFactory(WATER_FACTORY);
  pl.GetFactories().AddFactory(WATER_FACTORY);
  pl.GetFactories().AlterManning("UHHHUHB",4,1);

  pl.GetOwnedItems().AddItem(LABORATORY);
  pl.GetOwnedItems().AddItem(HEAVY_EQUIPMENT);
  pl.GetOwnedItems().AddItem(SCIENTISTS);
  pl.GetOwnedItems().AddItem(ROBOTS);
  pl.GetOwnedItems().AddItem(ROBOTS);
  pl.GetOwnedItems().AddItem(SPACE_STATION);

  pl.GetCommodityHand().AddCommodity(Commodity(WATER_COMMODITY,30,false,true));
  pl.GetCommodityHand().AddCommodity(Commodity(RESEARCH_COMMODITY,56,false,true));

  BOOST_CHECK_EQUAL(pl.GetCommodityHand().GetHandDescription(true,true),"|RE56M-WA30M|");

  BOOST_CHECK(pl.GetVP() == 1 + 2 + 3 + 10 + 20 + 5 + 1 + 3 + 3 + 2);

  BOOST_CHECK_EQUAL( pl.GetHighBid() , NOT_HIGH_BID );
  pl.SetHighBid(14);
  BOOST_CHECK_EQUAL( pl.GetHighBid() , 14 );
  
  BOOST_CHECK_EQUAL( pl.GetLastBid() , NOT_HIGH_BID );
  pl.SetLastBid(25);
  BOOST_CHECK_EQUAL( pl.GetLastBid() , 25);

  Player pl2;
  pl2 = pl;

  BOOST_CHECK(pl2.GetName() == "Test Name");
  BOOST_CHECK_EQUAL( pl2.GetId() , 14);
  BOOST_CHECK(pl2.OkStartup() == true);
  BOOST_CHECK(pl2.GetVP() == 1 + 2 + 3 + 10 + 20 + 5 + 1 + 3 + 3 + 2);
  BOOST_CHECK_EQUAL(pl2.GetCommodityHand().GetHandDescription(true,true),"|RE56M-WA30M|");
  BOOST_CHECK_EQUAL( pl2.GetPurchaseState() , INTERNALIZING );
  BOOST_CHECK_EQUAL( pl2.GetBidState() , PASS );
  BOOST_CHECK_EQUAL( pl2.HasPurchased() , true);
  BOOST_CHECK_EQUAL( pl2.GetNumHumans() , 8);
  BOOST_CHECK_EQUAL( pl2.GetNumRobots() , 28);
  BOOST_CHECK_EQUAL( pl2.GetHighBid() , 14 );
  BOOST_CHECK_EQUAL( pl2.GetLastBid() , 25 );
  

  Player pl3;
  SerialTransfer(pl,pl3);

  BOOST_CHECK(pl3.GetName() == "Test Name");
  BOOST_CHECK_EQUAL( pl3.GetId() , 14);
  BOOST_CHECK(pl3.OkStartup() == true);
  BOOST_CHECK(pl3.GetVP() == 1 + 2 + 3 + 10 + 20 + 5 + 1 + 3 + 3 + 2);
  BOOST_CHECK_EQUAL(pl3.GetCommodityHand().GetHandDescription(true,true),"|RE56M-WA30M|");
  BOOST_CHECK_EQUAL( pl3.GetPurchaseState() , INTERNALIZING );
  BOOST_CHECK_EQUAL( pl3.GetBidState() , PASS );
  BOOST_CHECK_EQUAL( pl3.HasPurchased() , true);
  BOOST_CHECK_EQUAL( pl3.GetNumHumans() , 8);
  BOOST_CHECK_EQUAL( pl3.GetNumRobots() , 28);
  BOOST_CHECK_EQUAL( pl3.GetHighBid() , 14 );
  BOOST_CHECK_EQUAL( pl3.GetLastBid() , 25 );
}

void AddFactories(Player &i_pl,FactoryType i_fac,int i_count,int i_mannedcount)
{
  int i;
  static std::string manning = "";
  static int manningcount = 0;

  manningcount += i_count;

  std::string newmanning;
  
  for (i = 0 ; i < i_count ; ++i)
  {
    i_pl.GetFactories().AddFactory(i_fac);
    
    if (i < i_mannedcount)
    {
      newmanning += "H";
    }
    else
    {
      newmanning += "U";
    }
  }
  manning = newmanning + manning;

  // this is testing a piece of Factories ensuring that order remains unchanged for existing factories.
  BOOST_CHECK(i_pl.GetFactories().AlterManning(manning,manningcount,0) == 0);
}

BOOST_AUTO_TEST_CASE( PlayerFactoryCount )
{
  Player pl("Counter",13);
  
  AddFactories(pl,MOON_BASE_FACTORY,3,1);
  AddFactories(pl,PLANETARY_CRUISER_FACTORY,4,2);
  AddFactories(pl,SPACE_STATION_FACTORY,5,2);
  AddFactories(pl,NEW_CHEMICALS_FACTORY,6,1);
  AddFactories(pl,RESEARCH_FACTORY,7,4);
  AddFactories(pl,TITANIUM_FACTORY,8,1);
  AddFactories(pl,WATER_FACTORY,9,3);
  AddFactories(pl,ORE_FACTORY,10,6);

  pl.GetOwnedItems().AddItem(SCIENTISTS);
  pl.GetOwnedItems().AddItem(SCIENTISTS);
  pl.GetOwnedItems().AddItem(ORBITAL_LAB);
  pl.GetOwnedItems().AddItem(ORBITAL_LAB);
  pl.GetOwnedItems().AddItem(ORBITAL_LAB);
  pl.GetOwnedItems().AddItem(DATA_LIBRARY);
  pl.GetOwnedItems().AddItem(WAREHOUSE);
  pl.GetOwnedItems().AddItem(HEAVY_EQUIPMENT);
  pl.GetOwnedItems().AddItem(NODULE);
  pl.GetOwnedItems().AddItem(ROBOTS);
  pl.GetOwnedItems().AddItem(LABORATORY);
  pl.GetOwnedItems().AddItem(ECOPLANTS);
  pl.GetOwnedItems().AddItem(OUTPOST);
  pl.GetOwnedItems().AddItem(SPACE_STATION);
  pl.GetOwnedItems().AddItem(PLANETARY_CRUISER);
  pl.GetOwnedItems().AddItem(MOON_BASE);

  // also testing out hand limit.
  BOOST_CHECK_EQUAL( pl.GetHandLimit(true) , 16 );
  BOOST_CHECK_EQUAL( pl.GetHandLimit(false) , 11 );

  BOOST_CHECK_EQUAL(pl.GetNumMannedFactories(ORE_COMMODITY) , 6);
  BOOST_CHECK_EQUAL(pl.GetNumUnmannedFactories(ORE_COMMODITY) , 4);
  BOOST_CHECK_EQUAL(pl.GetNumMannedFactories(WATER_COMMODITY) , 3);
  BOOST_CHECK_EQUAL(pl.GetNumUnmannedFactories(WATER_COMMODITY) , 6);
  BOOST_CHECK_EQUAL(pl.GetNumMannedFactories(TITANIUM_COMMODITY) , 1);
  BOOST_CHECK_EQUAL(pl.GetNumUnmannedFactories(TITANIUM_COMMODITY) , 7);
  BOOST_CHECK_EQUAL(pl.GetNumMannedFactories(RESEARCH_COMMODITY) , 6);
  BOOST_CHECK_EQUAL(pl.GetNumUnmannedFactories(RESEARCH_COMMODITY) , 3);
  BOOST_CHECK_EQUAL(pl.GetNumMannedFactories(MICROBIOTICS_COMMODITY) , 3);
  BOOST_CHECK_EQUAL(pl.GetNumUnmannedFactories(MICROBIOTICS_COMMODITY) , 0);
  BOOST_CHECK_EQUAL(pl.GetNumMannedFactories(NEW_CHEMICALS_COMMODITY) , 1);
  BOOST_CHECK_EQUAL(pl.GetNumUnmannedFactories(NEW_CHEMICALS_COMMODITY) , 5);
  BOOST_CHECK_EQUAL(pl.GetNumMannedFactories(ORBITAL_MEDICINE_COMMODITY) , 2);
  BOOST_CHECK_EQUAL(pl.GetNumUnmannedFactories(ORBITAL_MEDICINE_COMMODITY) , 3);
  BOOST_CHECK_EQUAL(pl.GetNumMannedFactories(RING_ORE_COMMODITY) , 2);
  BOOST_CHECK_EQUAL(pl.GetNumUnmannedFactories(RING_ORE_COMMODITY) , 2);
  BOOST_CHECK_EQUAL(pl.GetNumMannedFactories(MOON_ORE_COMMODITY) , 1);
  BOOST_CHECK_EQUAL(pl.GetNumUnmannedFactories(MOON_ORE_COMMODITY) , 2);



}

BOOST_AUTO_TEST_CASE( PlayerTestMaxHumans )
{
  Player pl("Player17",17);

  BOOST_CHECK_EQUAL( pl.GetMaxHumans() , 5);
  pl.GetOwnedItems().AddItem(OUTPOST);
  BOOST_CHECK_EQUAL( pl.GetMaxHumans() , 10);
  pl.GetOwnedItems().AddItem(OUTPOST);
  BOOST_CHECK_EQUAL( pl.GetMaxHumans() , 15);
  pl.GetFactories().AddFactory(MOON_BASE_FACTORY);
  pl.GetFactories().AlterManning("H",1,0);
  BOOST_CHECK_EQUAL( pl.GetMaxHumans() , 16);
  pl.GetFactories().AddFactory(PLANETARY_CRUISER_FACTORY);
  BOOST_CHECK_EQUAL( pl.GetMaxHumans() , 16);
  pl.GetFactories().AlterManning("HH",2,0);
  BOOST_CHECK_EQUAL( pl.GetMaxHumans() , 17);
}


BOOST_AUTO_TEST_CASE( PlayerTestMaxPurchasable )
{
  Player pl("ChienD'ArrenD'Or" , 111 );

  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, FIRST_UNLIMITED ) , 0) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, SECOND_UNLIMITED ) , 0) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );

  pl.GetCommodityHand().AddCommodity(Commodity(ORE_COMMODITY,3,false,false) );

  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, FIRST_UNLIMITED ) , 0) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, SECOND_UNLIMITED ) , 0) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );

  // 3 + 7
  pl.GetCommodityHand().AddCommodity(Commodity(ORE_COMMODITY,7,false,false) );

  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, FIRST_UNLIMITED ) , 1) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, SECOND_UNLIMITED ) , 1) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 1) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 1 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 1 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 1 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );

  // 3 + 7 + 10
  pl.GetCommodityHand().AddCommodity(Commodity(ORE_COMMODITY,10,false,false) );

  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, FIRST_UNLIMITED ) , 2) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, SECOND_UNLIMITED ) , 2) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 2) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 2 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 2 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 2 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 1 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 1 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 1 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );

  // 3 + 7 + 10 + 10
  pl.GetCommodityHand().AddCommodity(Commodity(ORE_COMMODITY,10,false,false) );

  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, FIRST_UNLIMITED ) , 3) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, SECOND_UNLIMITED ) , 3) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 3) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 3 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 3 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 3 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 1 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 1 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 1 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );

  // 3 + 7 + 10 + 10 + 10
  pl.GetCommodityHand().AddCommodity(Commodity(ORE_COMMODITY,10,false,false) );

  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, FIRST_UNLIMITED ) , 4) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, SECOND_UNLIMITED ) , 4) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 4) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 4 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 4 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 4 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 2 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 2 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 2 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );

  // 3 + 7 + 10 + 10 + 10 + 20
  pl.GetCommodityHand().AddCommodity(Commodity(ORE_COMMODITY,20,false,false) );

  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, FIRST_UNLIMITED ) , 5) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, SECOND_UNLIMITED ) , 5) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 5) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 6 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 6 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 6 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 3 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 3 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 3 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );

  pl.GetOwnedItems().AddItem(ROBOTS);

  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, FIRST_UNLIMITED ) , 6 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, FIRST_UNLIMITED ) , 5) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, SECOND_UNLIMITED ) , 5) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 5) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 6 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 6 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 6 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 3 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 3 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 3 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );

  pl.AddHumans(1);

  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, FIRST_UNLIMITED ) , 6 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, SECOND_UNLIMITED ) , 1 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 1 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, FIRST_UNLIMITED ) , 4) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, SECOND_UNLIMITED ) , 4) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 4) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 6 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 6 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 6 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 3 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 3 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 3 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );

  pl.GetOwnedItems().AddItem(ROBOTS);

  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, FIRST_UNLIMITED ) , 6 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, SECOND_UNLIMITED ) , 6 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 2 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, FIRST_UNLIMITED ) , 4) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, SECOND_UNLIMITED ) , 4) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 4) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 6 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 6 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 6 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 3 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 3 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 3 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );

  pl.AddRobots(2);

  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, FIRST_UNLIMITED ) , 6 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, SECOND_UNLIMITED ) , 6 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, FIRST_UNLIMITED ) , 4) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, SECOND_UNLIMITED ) , 4) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 4) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 6 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 6 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 6 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 3 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 3 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 3 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );

  pl.GetOwnedItems().AddItem(HEAVY_EQUIPMENT);

  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, FIRST_UNLIMITED ) , 6 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, SECOND_UNLIMITED ) , 6 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, FIRST_UNLIMITED ) , 4) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, SECOND_UNLIMITED ) , 4) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 4) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 6 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 6 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 6 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 3 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 3 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 3 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 2 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 2 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 2 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );

  pl.GetOwnedItems().AddItem(LABORATORY);

  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, FIRST_UNLIMITED ) , 6 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, SECOND_UNLIMITED ) , 6 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, FIRST_UNLIMITED ) , 4) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, SECOND_UNLIMITED ) , 4) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 4) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 6 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 6 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 6 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 3 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 3 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 3 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 2 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 2 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 2 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 1 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 1 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 1 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );

  // 3 + 7 + 10 + 10 + 10 + 20 + 60 (1 R)
  pl.GetCommodityHand().AddCommodity(Commodity(RESEARCH_COMMODITY,60,false,false) );

  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, FIRST_UNLIMITED ) , 12 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, SECOND_UNLIMITED ) , 12 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, FIRST_UNLIMITED ) , 4) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, SECOND_UNLIMITED ) , 4) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 4) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 12 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 12 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 12 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 6 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 6 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 6 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 4 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 4 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 4 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 3 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 3 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 3 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 1 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 1 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 1 );

  // 3 + 7 + 10 + 10 + 10 + 20 + 60 (1 R) | (120) + 120 (4R)
  pl.GetCommodityHand().AddCommodity(Commodity(RESEARCH_COMMODITY,120,false,true) );
  
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, FIRST_UNLIMITED ) , 24 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, SECOND_UNLIMITED ) , 24 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, FIRST_UNLIMITED ) , 4) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, SECOND_UNLIMITED ) , 4) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 4) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 24 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 24 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 24 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 12 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 12 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 12 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 8 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 8 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 8 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 6 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 6 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 6 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 4 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 4 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 4 );

  std::vector<Commodity> doomed;
  pl.GetCommodityHand().ApplyDeletes("11111111",doomed);

  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, FIRST_UNLIMITED ) , 0) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, SECOND_UNLIMITED ) , 0) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );

  pl.GetCommodityHand().AddCommodity(Commodity(RESEARCH_COMMODITY,7,false,false) );

  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, FIRST_UNLIMITED ) , 0) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, SECOND_UNLIMITED ) , 0) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
}

BOOST_AUTO_TEST_CASE( PlayerTestMaxPurchasable2 )
{
  Player pl("ChienD'ArrenD'Or" , 111 );

  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, FIRST_UNLIMITED ) , 0) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, SECOND_UNLIMITED ) , 0) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );

  // one robot per person, regardless.
  pl.GetOwnedItems().AddItem(ROBOTS);

  // 5 max pop
  // now there should be enough room for 3 humans and 1 robots.
  pl.AddHumans(2); // 3 more makes 5
  pl.AddRobots(1); // 1 more makes 2 = # of humans

  pl.GetCommodityHand().AddCommodity(Commodity(WATER_COMMODITY,50,false,false) );

  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, FIRST_UNLIMITED ) , 5 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, SECOND_UNLIMITED ) , 1 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ROBOT_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 1 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, FIRST_UNLIMITED ) , 3) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, SECOND_UNLIMITED ) , 3) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 3) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 5 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 5 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(ORE_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 5 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 2 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 2 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(WATER_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 2 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(TITANIUM_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(RESEARCH_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, FIRST_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, SECOND_UNLIMITED ) , 0 );
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(NEW_CHEMICALS_FACTORY_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 0 );
}

BOOST_AUTO_TEST_CASE( PlayerTestMaxPurchasable3 )
{
  Player pl("ChienD'ArrenD'Or" , 111 );
  pl.GetCommodityHand().AddCommodity(Commodity(WATER_COMMODITY,16,false,false) );

  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, FIRST_UNLIMITED ) , 1) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, SECOND_UNLIMITED ) , 1) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 1) ;

  pl.GetOwnedItems().AddItem(ECOPLANTS);
  pl.GetOwnedItems().AddItem(ECOPLANTS);
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, FIRST_UNLIMITED ) , 3) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, SECOND_UNLIMITED ) , 3) ;
  BOOST_CHECK_EQUAL( pl.GetMaxPurchasable(MAN_PURCHASABLE, ALWAYS_MULTIPLICATIVE ) , 3) ;
}

BOOST_AUTO_TEST_CASE( PlayerTestMaxRobots )
{
  Player pl("Chien D'Arren D'Or" , 303);

  pl.AddHumans(3);
  BOOST_CHECK_EQUAL( pl.GetMaxRobots( FIRST_UNLIMITED ) , 0);
  BOOST_CHECK_EQUAL( pl.GetMaxRobots( SECOND_UNLIMITED ) , 0);
  BOOST_CHECK_EQUAL( pl.GetMaxRobots( ALWAYS_MULTIPLICATIVE ) , 0);

  pl.GetOwnedItems().AddItem(ROBOTS);

  BOOST_CHECK_EQUAL( pl.GetMaxRobots( FIRST_UNLIMITED ) , UNLIMITED_ROBOTS);
  BOOST_CHECK_EQUAL( pl.GetMaxRobots( SECOND_UNLIMITED ) , 3);
  BOOST_CHECK_EQUAL( pl.GetMaxRobots( ALWAYS_MULTIPLICATIVE ) , 3);

  pl.GetOwnedItems().AddItem(ROBOTS);
  
  BOOST_CHECK_EQUAL( pl.GetMaxRobots( FIRST_UNLIMITED ) , UNLIMITED_ROBOTS);
  BOOST_CHECK_EQUAL( pl.GetMaxRobots( SECOND_UNLIMITED ) , UNLIMITED_ROBOTS);
  BOOST_CHECK_EQUAL( pl.GetMaxRobots( ALWAYS_MULTIPLICATIVE ) , 6);
  
  pl.GetOwnedItems().AddItem(ROBOTS);

  BOOST_CHECK_EQUAL( pl.GetMaxRobots( FIRST_UNLIMITED ) , UNLIMITED_ROBOTS);
  BOOST_CHECK_EQUAL( pl.GetMaxRobots( SECOND_UNLIMITED ) , UNLIMITED_ROBOTS);
  BOOST_CHECK_EQUAL( pl.GetMaxRobots( ALWAYS_MULTIPLICATIVE ) , 9);

  pl.AddHumans(2);

  BOOST_CHECK_EQUAL( pl.GetMaxRobots( FIRST_UNLIMITED ) , UNLIMITED_ROBOTS);
  BOOST_CHECK_EQUAL( pl.GetMaxRobots( SECOND_UNLIMITED ) , UNLIMITED_ROBOTS);
  BOOST_CHECK_EQUAL( pl.GetMaxRobots( ALWAYS_MULTIPLICATIVE ) , 15);

  pl.AddHumans(2); // this should take us up above the max # of humans

  BOOST_CHECK_EQUAL( pl.GetMaxRobots( FIRST_UNLIMITED ) , UNLIMITED_ROBOTS);
  BOOST_CHECK_EQUAL( pl.GetMaxRobots( SECOND_UNLIMITED ) , UNLIMITED_ROBOTS);
  BOOST_CHECK_EQUAL( pl.GetMaxRobots( ALWAYS_MULTIPLICATIVE ) , 15);

}


BOOST_AUTO_TEST_CASE( PlayerTestHasPurchasedAnything )
{
  Player pl("ChienD'ArrenD'Or", 111 );
  pl.AddHumans(3);

  BOOST_CHECK_EQUAL(pl.HasPurchasedAnything() , false);

  pl.AddHumans(1);
  BOOST_CHECK_EQUAL(pl.HasPurchasedAnything() , true);

  Player pl2("ChienD'ArrenD'Or", 111 );
  pl2.AddHumans(3);
  
  BOOST_CHECK_EQUAL(pl2.HasPurchasedAnything() , false);

  pl2.AddRobots(1);
  BOOST_CHECK_EQUAL(pl2.HasPurchasedAnything() , true);

  Player pl3("ChienD'ArrenD'Or", 111 );
  BOOST_CHECK_EQUAL(pl3.HasPurchasedAnything() , false);

  pl3.GetFactories().AddFactory(ORE_FACTORY);
  pl3.GetFactories().AddFactory(ORE_FACTORY);
  pl3.GetFactories().AddFactory(ORE_FACTORY);
  BOOST_CHECK_EQUAL(pl3.HasPurchasedAnything() , false);

  pl3.GetFactories().AddFactory(ORE_FACTORY);
  BOOST_CHECK_EQUAL(pl3.HasPurchasedAnything() , true);


  Player pl4("ChienD'ArrenD'Or", 111 );
  BOOST_CHECK_EQUAL(pl4.HasPurchasedAnything() , false);

  pl4.GetOwnedItems().AddItem(DATA_LIBRARY);
  BOOST_CHECK_EQUAL(pl4.HasPurchasedAnything() , true);

}
  
BOOST_AUTO_TEST_CASE( PlayerTestAutoMan )
{
  Player pl("Tolinka", 333 );
  
  // case 1.  more humans than factories.
  pl.AddHumans(4);
  pl.GetFactories().AddFactory(WATER_FACTORY);
  pl.GetFactories().AddFactory(NEW_CHEMICALS_FACTORY);
  pl.GetFactories().AddFactory(RESEARCH_FACTORY);

  pl.AutoMan();
  BOOST_CHECK_EQUAL( pl.GetFactories().GetFactoryDescription(),"|WH-RH-NH|");

  // case 2. more factories than humans
  Player pl2("Tai'ra", 444 );
  pl2.AddHumans(4);
  pl2.GetFactories().AddFactory(WATER_FACTORY);
  pl2.GetFactories().AddFactory(NEW_CHEMICALS_FACTORY);
  pl2.GetFactories().AddFactory(RESEARCH_FACTORY);
  pl2.GetFactories().AddFactory(ORE_FACTORY);
  pl2.GetFactories().AddFactory(ORE_FACTORY);

  pl2.AutoMan();
  BOOST_CHECK_EQUAL( pl2.GetFactories().GetFactoryDescription(),"|OU-OH-WH-RH-NH|");

  // case 3. fewer humans, but more humans+robots, than factories
  Player pl3("Myrddyn", 555 );
  pl3.AddHumans(2);
  pl3.AddRobots(3);
  pl3.GetFactories().AddFactory(WATER_FACTORY);
  pl3.GetFactories().AddFactory(NEW_CHEMICALS_FACTORY);
  pl3.GetFactories().AddFactory(RESEARCH_FACTORY);
  pl3.GetFactories().AddFactory(ORE_FACTORY);

  pl3.AutoMan();
  BOOST_CHECK_EQUAL( pl3.GetFactories().GetFactoryDescription(),"|OB-WB-RH-NH|");

  // case 4. fewer humans+robots than factories

  Player pl4("Justin", 777);
  pl4.AddHumans(2);
  pl4.AddRobots(3);

  pl4.GetFactories().AddFactory(WATER_FACTORY);
  pl4.GetFactories().AddFactory(NEW_CHEMICALS_FACTORY);
  pl4.GetFactories().AddFactory(RESEARCH_FACTORY);
  pl4.GetFactories().AddFactory(WATER_FACTORY);
  pl4.GetFactories().AddFactory(ORE_FACTORY);
  pl4.GetFactories().AddFactory(ORE_FACTORY);

  pl4.AutoMan();
  BOOST_CHECK_EQUAL( pl4.GetFactories().GetFactoryDescription(),"|OU-OB-WB-WB-RH-NH|");

}


